#include "../cmd/confext.h"
#include "../cmd/process.h"
#include "../cmd/logging.h"

#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <algorithm>

namespace fs = std::filesystem;

namespace debostree::confext {

ConfextMode parse_mode(const std::string& name) {
    if (name == "none")     return ConfextMode::None;
    if (name == "separate") return ConfextMode::Separate;
    if (name == "usr-etc")  return ConfextMode::UsrEtc;
    throw std::invalid_argument("Nieznany tryb confext: '" + name +
                                "'. Dostepne: none, separate, usr-etc");
}

std::vector<std::string> filter_etc_files(const std::vector<std::string>& files) {
    std::vector<std::string> etc;
    for (auto& f : files) {
        if (f.rfind("/etc/", 0) == 0 || f == "/etc")
            etc.push_back(f);
    }
    return etc;
}

ConfextResult process_etc_files(const std::string& rootfs_path,
                                 const std::string& pkg_name,
                                 const std::vector<std::string>& etc_files,
                                 ConfextMode mode)
{
    ConfextResult result;

    if (mode == ConfextMode::None || etc_files.empty()) {
        log::debug("confext: tryb None lub brak plikow /etc -- pomijam");
        return result;
    }

    if (mode == ConfextMode::UsrEtc) {
        /* Przenies /etc/<plik> -> /usr/etc/<plik> w rootfs.
         * Symlink /etc/<plik> -> /usr/etc/<plik> nie jest tworzony --
         * uzytkownik odpowiada za konfiguracje systemu. */
        std::string usr_etc = rootfs_path + "/usr/etc";
        fs::create_directories(usr_etc);

        for (auto& f : etc_files) {
            /* f = "/etc/vim/vimrc" -> docelowe "/usr/etc/vim/vimrc" */
            std::string rel = f.substr(4); /* usun "/etc" prefix */
            std::string src  = rootfs_path + f;
            std::string dst  = rootfs_path + "/usr" + f;

            if (!fs::exists(src)) continue;

            fs::create_directories(fs::path(dst).parent_path());
            std::error_code ec;
            fs::rename(src, dst, ec);
            if (!ec) {
                result.moved_files.push_back(f);
                log::debug("confext[usr-etc]: " + f + " -> /usr" + f);
            } else {
                log::warn("confext[usr-etc]: nie mozna przeniesc " + f + ": " + ec.message());
            }
        }
        log::info("confext: przeniesiono " + std::to_string(result.moved_files.size()) +
                  " plikow /etc -> /usr/etc dla " + pkg_name);
        return result;
    }

    if (mode == ConfextMode::Separate) {
        /* Tworzy layout confext zgodny z systemd.confext(7):
         *
         * /etc/extensions/<pkg_name>/
         *   usr/
         *     lib/
         *       extension-release.d/
         *         extension-release.<pkg_name>   -- metadane
         *   etc/                                 -- pliki konfiguracyjne
         *     <plik>
         */
        std::string ext_base = rootfs_path + "/etc/extensions/" + pkg_name;
        std::string ext_etc  = ext_base + "/etc";
        std::string ext_meta = ext_base + "/usr/lib/extension-release.d";

        fs::create_directories(ext_etc);
        fs::create_directories(ext_meta);

        /* Metadane extension-release */
        std::string meta_path = ext_meta + "/extension-release." + pkg_name;
        {
            std::ofstream mf(meta_path, std::ios::trunc);
            mf << "# systemd-confext extension release metadata\n"
               << "# Generated by deb-ostree v0.2.0\n"
               << "ID=debian\n"
               << "SYSEXT_SCOPE=system\n"
               << "EXTENSION_RELOAD_MANAGER=1\n";
        }
        log::debug("confext: metadane -> " + meta_path);

        /* Przenies pliki /etc do extension */
        for (auto& f : etc_files) {
            std::string src = rootfs_path + f;
            /* /etc/vim/vimrc -> /etc/extensions/<pkg>/etc/vim/vimrc */
            std::string dst = ext_base + f;

            if (!fs::exists(src)) continue;

            fs::create_directories(fs::path(dst).parent_path());
            std::error_code ec;
            fs::rename(src, dst, ec);
            if (!ec) {
                result.moved_files.push_back(f);
                log::debug("confext[separate]: " + f + " -> extension/" + pkg_name);
            } else {
                log::warn("confext[separate]: nie mozna przeniesc " + f + ": " + ec.message());
            }
        }

        result.extension_dir = ext_base;
        log::info("confext: extension '" + pkg_name + "' utworzony w " + ext_base +
                  " (" + std::to_string(result.moved_files.size()) + " plikow)");
        return result;
    }

    return result;
}

bool activate_confext(const std::string& rootfs_path) {
    /* Sprawdz czy systemd-confext jest dostepny w chroot */
    std::string confext_bin = rootfs_path + "/usr/bin/systemd-confext";
    if (!fs::exists(confext_bin)) {
        confext_bin = rootfs_path + "/bin/systemd-confext";
        if (!fs::exists(confext_bin)) {
            log::debug("confext: systemd-confext niedostepny w " + rootfs_path);
            return false;
        }
    }

    /* Wywolaj systemd-confext merge w chroot (jesli mamy root) */
    auto r = process::run({"chroot", rootfs_path, "systemd-confext", "merge"});
    if (!r.ok()) {
        log::warn("confext: systemd-confext merge nie powiodlo sie: " + r.stderr_data);
        return false;
    }
    log::info("confext: systemd-confext merge OK");
    return true;
}

} // namespace debostree::confext
